specVersion: "0.2.0"

name: "subql-dictionary"
version: "0.0.1"
description: A subquery project provide dictionary data & service for a substrate-based network
repository: ""

schema:
  file: "./schema.graphql"

dataSources:
  - kind: substrate/Runtime
    # startBlock: 1
    startBlock: 6345000 # Darwinia

    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler

network:
  # Polkadot
  # genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  # endpoint: wss://polkadot.api.onfinality.io/public-ws
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot

  # KSM
  # genesisHash: "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
  # endpoint: wss://kusama.api.onfinality.io/public-ws
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-kusama

  # Darwinia
  genesisHash: "0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8"
  endpoint: wss://rpc.darwinia.network

  # CRAB
  # genesisHash: '0x34f61bfda344b3fad3c3e38832a91448b3c613b199eb23e5110a635d71c13c65'
  # endpoint: wss://crab-rpc.darwinia.network

  # pangolin
  # genesisHash: "0xce44bd16fc276f9e457b452577b6c2678e57768260012af127479fed806da7e7"
  # endpoint: wss://pangolin-rpc.darwinia.network/

  chaintypes:
    # file: "./types_pangolin.yaml"
    file: "./types_darwinia.yaml"
    # file: './types_crab.yaml'
